#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc wm -O DP-0 HDMI-0
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-0 --mode 1280x1024 --rotate normal --left-of HDMI-0
xsetroot -cursor_name left_ptr

# reorder the list of monitors to match the given order
start_from=1
monitors_connected=$(bspc query -M | wc -l)
per_monitor=$(( 6 / monitors_connected ))
#for monitor in $(bspc query -M | tac); do
for monitor in $(bspc query -M); do
	bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor - 1)))
	start_from=$(( start_from + per_monitor ))
done

bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config border_width         2
bspc config window_gap           10

#bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout us,ru -option grp:alt_shift_toggle      # keymaps
feh --bg-fill $HOME/Media/default.jpg                     # background
$HOME/.config/polybar/launch.sh                           # status bar
